version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5440:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
